services:

  nginx:
    networks:
      - tsd-network
    build:
      context: srcs/frontend
      dockerfile: "Dockerfile"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - ./srcs/frontend/srcs:/usr/share/nginx/html
      - media:/media
    restart: unless-stopped

  django:
    networks:
      - tsd-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - media:/app/avatars
    build:
      context: srcs/backend
      dockerfile: "Dockerfile"
    env_file:
      - .env
    restart: unless-stopped

  redis:
    networks:
      - tsd-network
    image: redis:7.4.1
    volumes:
      - db:/data
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1"]

  postgres:
    networks:
      - tsd-network
    image: postgres:17
    #can keep ports open for now, but need to close them later on
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped

networks:
  tsd-network:
    driver: bridge

volumes:
  db:
  media:
